import { Resource } from '../types';

export const SEED_RESOURCES: Resource[] = [
  // ==========================================
  // 1. BUILD — CODING AGENTS (Verified)
  // ==========================================
  {
    id: 'res-opencode',
    title: 'OpenCode',
    description: 'Open-source coding agent designed for terminal and editor environments with multi-provider and local model flexibility.',
    url: 'https://github.com/opencode-ai/opencode',
    resourceType: 'coding_agent',
    category: 'BUILD',
    subcategory: 'AI Coding Agents',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free and Open Source. Zero licensing cost (Bring your own API key or run free local models via Ollama).',
    license: 'Apache 2.0',
    platform: ['Terminal', 'VS Code', 'CLI'],
    difficulty: 'Intermediate',
    technicalLevel: 'Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched'],
    founderGoals: ['Build MVP faster', 'Zero software cost', 'Local model privacy'],
    useCases: ['Autonomous code generation', 'Refactoring legacy repos', 'Offline AI coding'],
    skillsRequired: ['Terminal CLI', 'Git basics'],
    timeToLearn: '20 mins',
    recommendedFor: 'Founders who want an open-source coding agent without vendor lock-in or recurring subscriptions.',
    tags: ['Coding Agent', 'Open Source', 'Local Models', 'Terminal', 'CLI'],
    qualityScore: 93,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 9,
      community: 8,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'High-leverage open-source coding agent that executes tasks directly in the filesystem. Excellent local model support via Ollama avoids API token bills.',
    lastVerifiedAt: '2026-08',
    source: 'Official GitHub Repository',
    status: 'active',
    createdAt: '2026-01-10',
    updatedAt: '2026-08-20',
    codingAgentDetails: {
      supportedEnvironments: ['Terminal', 'VS Code', 'Docker'],
      localModelSupport: true,
      modelFlexibility: 'Ollama, LM Studio, OpenAI, Anthropic, Gemini, DeepSeek',
      repositoryUrl: 'https://github.com/opencode-ai/opencode',
      documentationUrl: 'https://github.com/opencode-ai/opencode#readme',
      setupDifficulty: 'Easy',
      license: 'Apache 2.0'
    },
    isFeatured: true
  },
  {
    id: 'res-cline',
    title: 'Cline (Autonomous VS Code Agent)',
    description: 'Open-source autonomous AI coding assistant extension for VS Code that reads files, writes code, executes terminal commands, and browses documentation.',
    url: 'https://github.com/cline/cline',
    resourceType: 'coding_agent',
    category: 'BUILD',
    subcategory: 'AI Coding Agents',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free extension. Connect to local LLMs (Ollama) or custom API endpoints with zero markup.',
    license: 'Apache 2.0',
    platform: ['VS Code', 'VSCodium', 'Cursor'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue'],
    founderGoals: ['Ship features in hours', 'Fix bugs autonomously', 'Full terminal agency'],
    useCases: ['End-to-end fullstack feature building', 'Writing unit tests', 'Automated bug resolution'],
    skillsRequired: ['Basic VS Code usage'],
    timeToLearn: '10 mins',
    recommendedFor: 'Solo founders wanting a powerful agent inside their daily editor with granular step-by-step human confirmation.',
    tags: ['VS Code', 'Coding Agent', 'Open Source', 'Autonomous', 'Editor Extension'],
    qualityScore: 96,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 9,
      recency: 10,
      practicalValue: 10
    },
    qualityExplanation: 'Verified open source with active community maintenance. Provides full autonomous multi-file edits with clear human-in-the-loop permission prompts.',
    lastVerifiedAt: '2026-08',
    source: 'Official GitHub & VS Code Marketplace',
    status: 'active',
    createdAt: '2026-01-15',
    updatedAt: '2026-08-25',
    codingAgentDetails: {
      supportedEnvironments: ['VS Code', 'VSCodium'],
      localModelSupport: true,
      modelFlexibility: 'OpenRouter, Ollama, Anthropic, OpenAI, Gemini, Custom OpenAI-compatible',
      repositoryUrl: 'https://github.com/cline/cline',
      documentationUrl: 'https://github.com/cline/cline#readme',
      setupDifficulty: 'Easy',
      license: 'Apache 2.0'
    },
    isFeatured: true
  },
  {
    id: 'res-openhands',
    title: 'OpenHands (Platform for Software Agents)',
    description: 'Open-source platform for AI software developers that can write code, run shell commands, and interact with web browsers in sandboxed Docker environments.',
    url: 'https://github.com/All-Hands-AI/OpenHands',
    resourceType: 'coding_agent',
    category: 'BUILD',
    subcategory: 'AI Coding Agents',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: 'Self-hosted version is 100% free and open-source under MIT license.',
    license: 'MIT',
    platform: ['Docker', 'Web UI', 'CLI', 'Self-Hosted'],
    difficulty: 'Intermediate',
    technicalLevel: 'Technical',
    startupStages: ['Building MVP', 'Launched', 'Growing'],
    founderGoals: ['Automate GitHub PR reviews', 'Autonomous bug fixing in isolated container'],
    useCases: ['Autonomous issue resolution', 'Docker sandbox execution', 'Benchmark evaluation'],
    skillsRequired: ['Docker', 'Terminal CLI'],
    timeToLearn: '30 mins',
    recommendedFor: 'Founders needing sandboxed automated agent execution for complex repositories.',
    tags: ['Coding Agent', 'Open Source', 'Docker Sandbox', 'Autonomous', 'MIT'],
    qualityScore: 91,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 9,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 9,
      maintenance: 10,
      community: 9,
      recency: 9,
      practicalValue: 9
    },
    qualityExplanation: 'Robust sandboxed runtime that prevents agents from accidentally executing destructive commands on the host machine.',
    lastVerifiedAt: '2026-08',
    source: 'Official GitHub Organization',
    status: 'active',
    createdAt: '2026-02-01',
    updatedAt: '2026-08-22',
    codingAgentDetails: {
      supportedEnvironments: ['Docker', 'Web UI', 'CLI'],
      localModelSupport: true,
      modelFlexibility: 'LiteLLM backend (100+ providers + Local Ollama)',
      repositoryUrl: 'https://github.com/All-Hands-AI/OpenHands',
      documentationUrl: 'https://docs.all-hands.dev',
      setupDifficulty: 'Medium',
      license: 'MIT'
    }
  },
  {
    id: 'res-aider',
    title: 'Aider (Git-Native Pair Programming)',
    description: 'Terminal-based AI pair programmer that integrates tightly with Git, automatically writing clean commit messages for each code change.',
    url: 'https://github.com/paul-gauthier/aider',
    resourceType: 'coding_agent',
    category: 'BUILD',
    subcategory: 'AI Coding Agents',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free and open-source CLI tool under Apache 2.0.',
    license: 'Apache 2.0',
    platform: ['Terminal CLI', 'Mac', 'Linux', 'Windows'],
    difficulty: 'Intermediate',
    technicalLevel: 'Technical',
    startupStages: ['Validating', 'Building MVP', 'Launched'],
    founderGoals: ['Git-backed code generation', 'Refactoring without leaving the terminal'],
    useCases: ['Multi-file edits', 'Git repo automated commits', 'Voice-to-code coding in terminal'],
    skillsRequired: ['Git workflow', 'Command line'],
    timeToLearn: '15 mins',
    recommendedFor: 'Technical founders who live in the terminal and want precise Git branch commit control.',
    tags: ['Pair Programming', 'Git Native', 'CLI', 'Open Source', 'Terminal'],
    qualityScore: 94,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 9,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Consistently ranks at top of coding benchmarks for edit accuracy and map-of-repo context retrieval.',
    lastVerifiedAt: '2026-08',
    source: 'Official GitHub Repository',
    status: 'active',
    createdAt: '2026-01-20',
    updatedAt: '2026-08-24',
    codingAgentDetails: {
      supportedEnvironments: ['Terminal CLI', 'VS Code terminal', 'Any Shell'],
      localModelSupport: true,
      modelFlexibility: 'Claude, OpenAI, DeepSeek, Ollama, Local llama.cpp',
      repositoryUrl: 'https://github.com/paul-gauthier/aider',
      documentationUrl: 'https://aider.chat/docs',
      setupDifficulty: 'Easy',
      license: 'Apache 2.0'
    },
    isFeatured: true
  },
  {
    id: 'res-continue',
    title: 'Continue.dev',
    description: 'Open-source autopilot for software development that brings AI chat and tab-autocomplete directly into VS Code and JetBrains IDEs.',
    url: 'https://github.com/continuedev/continue',
    resourceType: 'coding_agent',
    category: 'BUILD',
    subcategory: 'AI Coding Agents',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free & Open Source Apache 2.0 extension.',
    license: 'Apache 2.0',
    platform: ['VS Code', 'JetBrains', 'VSCodium'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Building MVP', 'Launched', 'Growing'],
    founderGoals: ['Inline tab autocomplete', 'Codebase indexation and Q&A'],
    useCases: ['Fast autocompletion', 'Explaining complex libraries', 'Unit test generation'],
    skillsRequired: ['IDE familiarity'],
    timeToLearn: '5 mins',
    recommendedFor: 'Founders who want Copilot-style inline tab autocomplete without paying $20/month.',
    tags: ['Autocomplete', 'IDE Extension', 'Open Source', 'JetBrains', 'VS Code'],
    qualityScore: 92,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 9,
      maintenance: 9,
      community: 9,
      recency: 9,
      practicalValue: 9
    },
    qualityExplanation: 'Seamless drop-in replacement for paid autocomplete tools with full privacy and local model compatibility.',
    lastVerifiedAt: '2026-08',
    source: 'Official Website & GitHub',
    status: 'active',
    createdAt: '2026-02-05',
    updatedAt: '2026-08-20',
    codingAgentDetails: {
      supportedEnvironments: ['VS Code', 'JetBrains IDEs (IntelliJ, PyCharm, WebStorm)'],
      localModelSupport: true,
      modelFlexibility: 'Ollama, LM Studio, Anthropic, Gemini, OpenAI, Groq',
      repositoryUrl: 'https://github.com/continuedev/continue',
      documentationUrl: 'https://docs.continue.dev',
      setupDifficulty: 'Easy',
      license: 'Apache 2.0'
    }
  },
  {
    id: 'res-goose',
    title: 'Goose (On-Machine AI Agent by Block)',
    description: 'Open-source, extensible AI agent that automates complex engineering tasks, runs shell commands, and builds software directly on your machine.',
    url: 'https://github.com/block/goose',
    resourceType: 'coding_agent',
    category: 'BUILD',
    subcategory: 'AI Coding Agents',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free Apache 2.0 open-source agent.',
    license: 'Apache 2.0',
    platform: ['CLI', 'Desktop App', 'Mac', 'Linux', 'Windows'],
    difficulty: 'Intermediate',
    technicalLevel: 'Technical',
    startupStages: ['Building MVP', 'Launched'],
    founderGoals: ['Automate workflow scripting', 'Tool extension with MCP protocol'],
    useCases: ['Repository refactoring', 'System script automation', 'MCP tool integrations'],
    skillsRequired: ['Terminal', 'Python / Rust knowledge helpful'],
    timeToLearn: '25 mins',
    recommendedFor: 'Founders building multi-tool automation workflows powered by Model Context Protocol (MCP).',
    tags: ['Goose', 'Block', 'MCP', 'Open Source', 'Autonomous Agent'],
    qualityScore: 90,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 8,
      maintenance: 9,
      community: 8,
      recency: 10,
      practicalValue: 8
    },
    qualityExplanation: 'Backed by Block engineering with native Model Context Protocol (MCP) tool support.',
    lastVerifiedAt: '2026-08',
    source: 'Official Block GitHub',
    status: 'active',
    createdAt: '2026-03-01',
    updatedAt: '2026-08-18',
    codingAgentDetails: {
      supportedEnvironments: ['CLI', 'Desktop GUI'],
      localModelSupport: true,
      modelFlexibility: 'Ollama, Databricks, OpenAI, Anthropic, Gemini',
      repositoryUrl: 'https://github.com/block/goose',
      documentationUrl: 'https://block.github.io/goose',
      setupDifficulty: 'Medium',
      license: 'Apache 2.0'
    }
  },

  // ==========================================
  // 2. BUILD — FREE & OPEN SOURCE IDES
  // ==========================================
  {
    id: 'res-vscodium',
    title: 'VSCodium (Libre VS Code Build)',
    description: 'Community-driven, freely-licensed binary distribution of Microsoft’s editor VS Code without telemetry, tracking, or proprietary branding.',
    url: 'https://vscodium.com',
    resourceType: 'ide',
    category: 'BUILD',
    subcategory: 'IDEs & Editors',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free and Libre Open Source Software (FLOSS) under MIT license.',
    license: 'MIT',
    platform: ['Mac', 'Windows', 'Linux'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Zero telemetry development', 'Lightweight full-featured editor'],
    useCases: ['Web development', 'Fullstack coding', 'Open VSX extension access'],
    skillsRequired: ['General computer navigation'],
    timeToLearn: '10 mins',
    recommendedFor: 'Founders who want full VS Code capabilities with zero telemetry, data tracking, or Microsoft vendor lock-in.',
    tags: ['IDE', 'FLOSS', 'Open Source', 'VSCodium', 'Privacy'],
    qualityScore: 95,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 10,
      community: 9,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Pure open-source binaries compiled directly from the vscode repository source. Safe, lightweight, and completely telemetry-free.',
    lastVerifiedAt: '2026-08',
    source: 'Official VSCodium Website',
    status: 'active',
    createdAt: '2026-01-05',
    updatedAt: '2026-08-20',
    ideDetails: {
      platform: ['Mac (Apple Silicon & Intel)', 'Windows', 'Linux (deb/rpm/flatpak)'],
      languageSupport: ['TypeScript', 'JavaScript', 'Python', 'Go', 'Rust', 'All via LSP'],
      extensions: 'Open VSX Registry + standard .vsix extensions',
      aiSupport: 'Supports Cline, Continue, Aider, OpenCode',
      offlineSupport: true,
      isOpenSource: true,
      bestUseCase: 'General-purpose fullstack and frontend web application development'
    },
    isFeatured: true
  },
  {
    id: 'res-zed',
    title: 'Zed Editor',
    description: 'High-performance, multiplayer code editor written in Rust with instant startup times, low memory consumption, and native AI integration.',
    url: 'https://zed.dev',
    resourceType: 'ide',
    category: 'BUILD',
    subcategory: 'IDEs & Editors',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free and Open Source (GPL & Apache 2.0). Free collaborative editing.',
    license: 'GPLv3 / Apache 2.0',
    platform: ['Mac', 'Linux', 'Windows (Beta)'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Building MVP', 'Launched', 'Growing'],
    founderGoals: ['Blazing fast editor speed', 'Pair programming with remote co-founder'],
    useCases: ['Fast editing on laptops with low battery usage', 'Real-time collaborative pair programming'],
    skillsRequired: ['Basic code editing'],
    timeToLearn: '10 mins',
    recommendedFor: 'Founders on Mac/Linux who hate editor lag and want instant file jumping with native AI assistance.',
    tags: ['Zed', 'Rust', 'High Performance', 'Open Source', 'Pair Programming'],
    qualityScore: 94,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 9,
      maintenance: 10,
      community: 9,
      recency: 10,
      practicalValue: 9
    },
    qualityExplanation: 'GPU-accelerated text rendering with zero input lag. Built-in multiplayer workspaces make co-founder pairing painless.',
    lastVerifiedAt: '2026-08',
    source: 'Official Zed Website & GitHub',
    status: 'active',
    createdAt: '2026-02-01',
    updatedAt: '2026-08-25',
    ideDetails: {
      platform: ['macOS', 'Linux', 'Windows (Preview)'],
      languageSupport: ['Rust', 'TypeScript', 'Python', 'Go', 'HTML/CSS', 'Elixir'],
      extensions: 'Growing community extension catalog',
      aiSupport: 'Native Assistant Panel + inline transformations (Anthropic, OpenAI, Ollama)',
      offlineSupport: true,
      isOpenSource: true,
      bestUseCase: 'High-speed code navigation and frictionless pair programming'
    }
  },
  {
    id: 'res-neovim',
    title: 'Neovim',
    description: 'Hyperextensible, terminal-based modal text editor focused on speed, extensibility with Lua, and built-in Language Server Protocol (LSP).',
    url: 'https://neovim.io',
    resourceType: 'ide',
    category: 'BUILD',
    subcategory: 'IDEs & Editors',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free and Open Source (Apache 2.0 / Vim License). Zero cost forever.',
    license: 'Apache 2.0',
    platform: ['Terminal', 'Mac', 'Linux', 'Windows', 'SSH Remote'],
    difficulty: 'Advanced',
    technicalLevel: 'Advanced Dev',
    startupStages: ['Building MVP', 'Launched', 'Growing'],
    founderGoals: ['Keyboard-only speed', 'Remote server development via SSH'],
    useCases: ['Modal editing', 'Coding over SSH on low-spec cloud VPS', 'Customized dev workflows'],
    skillsRequired: ['Vim motions', 'Lua / Shell config'],
    timeToLearn: '40+ hours',
    recommendedFor: 'Advanced technical founders who want the fastest possible keyboard navigation without touching a mouse.',
    tags: ['Neovim', 'Modal Editing', 'Lua', 'Terminal', 'Open Source'],
    qualityScore: 91,
    qualityBreakdown: {
      relevance: 8,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 8,
      maintenance: 10,
      community: 10,
      recency: 9,
      practicalValue: 8
    },
    qualityExplanation: 'Maximum possible developer velocity for experienced modal typists; extremely lightweight footprint.',
    lastVerifiedAt: '2026-08',
    source: 'Official Neovim Website',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-15',
    ideDetails: {
      platform: ['Cross-platform POSIX', 'macOS', 'Linux', 'Windows'],
      languageSupport: ['Any language via Treesitter & LSP'],
      extensions: 'Vibrant Lua plugin ecosystem (Lazy.nvim, Mason, Telescope)',
      aiSupport: 'Avante.nvim, CodeCompanion.nvim, Copilot.lua, Aider',
      offlineSupport: true,
      isOpenSource: true,
      bestUseCase: 'Keyboard-driven editing and remote server management'
    }
  },

  // ==========================================
  // 3. BUILD — BACKEND, DATABASE, HOSTING & UI
  // ==========================================
  {
    id: 'res-supabase',
    title: 'Supabase (Open Source Firebase Alternative)',
    description: 'PostgreSQL database backend with instant REST/GraphQL APIs, Auth, Realtime listeners, Storage, and Vector embeddings.',
    url: 'https://supabase.com',
    resourceType: 'tool',
    category: 'BUILD',
    subcategory: 'Databases & Backend',
    pricingType: 'free_tier',
    isOpenSource: true,
    isFree: false,
    hasFreeTier: true,
    freeTierDescription: 'Free Tier includes 2 active Postgres databases, 500MB storage, 50,000 monthly active users (MAU), 5GB bandwidth, and 1GB file storage.',
    license: 'Apache 2.0 (Self-Hostable)',
    platform: ['Cloud Managed', 'Self-Hosted Docker'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue'],
    founderGoals: ['Launch backend in 10 minutes', 'Zero backend maintenance cost', 'Postgres SQL power'],
    useCases: ['User authentication', 'Relational database', 'Vector search for AI'],
    skillsRequired: ['Basic SQL or JavaScript SDK'],
    timeToLearn: '30 mins',
    recommendedFor: 'Founders building web or mobile apps needing an instant production-ready SQL database with built-in login.',
    tags: ['Postgres', 'Backend', 'Authentication', 'Open Source', 'Free Tier'],
    qualityScore: 97,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 9,
      openSource: 10,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 10,
      practicalValue: 10
    },
    qualityExplanation: 'The standard backend choice for solo builders. Excellent free tier and full SQL access prevents proprietary database lock-in.',
    lastVerifiedAt: '2026-08',
    source: 'Official Supabase Pricing & Docs',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-26',
    isFeatured: true
  },
  {
    id: 'res-cloudflare-pages',
    title: 'Cloudflare Pages & Workers',
    description: 'Zero-cost serverless hosting and edge compute platform with unlimited bandwidth, free custom domains, and automatic SSL.',
    url: 'https://pages.cloudflare.com',
    resourceType: 'tool',
    category: 'BUILD',
    subcategory: 'Hosting & Deployment',
    pricingType: 'free_tier',
    isOpenSource: false,
    isFree: false,
    hasFreeTier: true,
    freeTierDescription: 'Free plan: Unlimited bandwidth, unlimited static requests, 500 builds/month, and 100,000 free serverless Worker executions/day.',
    platform: ['Web', 'CLI / Wrangler'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Never pay for bandwidth', 'Host landing pages & web apps with 0 latency'],
    useCases: ['Next.js / Vite SPA deployment', 'Custom domain SSL setup', 'Edge API endpoints'],
    skillsRequired: ['Git push to deploy'],
    timeToLearn: '15 mins',
    recommendedFor: 'Founders who want to avoid unexpected bandwidth bills when their product goes viral on Reddit or Hacker News.',
    tags: ['Hosting', 'Free Bandwidth', 'Edge CDN', 'Deployment', 'Free Tier'],
    qualityScore: 96,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 6,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 10,
      community: 9,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Unlike competitors that charge after 100GB bandwidth, Cloudflare Pages offers genuinely unlimited static bandwidth on its free tier.',
    lastVerifiedAt: '2026-08',
    source: 'Official Cloudflare Pricing',
    status: 'active',
    createdAt: '2026-01-10',
    updatedAt: '2026-08-20'
  },
  {
    id: 'res-shadcn-ui',
    title: 'shadcn/ui',
    description: 'Beautifully designed, accessible, copy-and-paste React & Tailwind components that you own 100% in your codebase.',
    url: 'https://ui.shadcn.com',
    resourceType: 'template',
    category: 'BUILD',
    subcategory: 'UI/UX & Design',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free & Open Source (MIT). Not an npm dependency — you own the code.',
    license: 'MIT',
    platform: ['React', 'Next.js', 'Vite', 'Tailwind CSS'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched'],
    founderGoals: ['Build world-class UI without a designer', 'Full accessibility out of the box'],
    useCases: ['Dashboards', 'Forms', 'Modals', 'Dropdowns', 'Landing page UI'],
    skillsRequired: ['React', 'Tailwind CSS'],
    timeToLearn: '15 mins',
    recommendedFor: 'Solo founders building SaaS applications who want clean, accessible, modern UI in minutes.',
    tags: ['UI Components', 'Tailwind CSS', 'Accessible', 'Open Source', 'Design System'],
    qualityScore: 98,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 10,
      practicalValue: 10
    },
    qualityExplanation: 'Revolutionized frontend developer experience. Code is pasted directly into your repository, giving you zero library lock-in.',
    lastVerifiedAt: '2026-08',
    source: 'Official GitHub & Website',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-25',
    isFeatured: true
  },
  {
    id: 'res-posthog',
    title: 'PostHog (Open Source Product OS)',
    description: 'All-in-one product analytics suite combining user funnels, session recordings, feature flags, A/B testing, and user feedback surveys.',
    url: 'https://posthog.com',
    resourceType: 'tool',
    category: 'BUILD',
    subcategory: 'Analytics & Monitoring',
    pricingType: 'free_tier',
    isOpenSource: true,
    isFree: false,
    hasFreeTier: true,
    freeTierDescription: 'Generous Free Tier: 1 Million free events/month, 5,000 free session recordings/month, 250 survey responses, and unlimited feature flags.',
    license: 'MIT (Self-Hostable) / Cloud Hosted',
    platform: ['Web', 'Mobile', 'Node.js', 'Python'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Diagnose user drop-off with screen replays', 'Track product retention funnels'],
    useCases: ['Session replay debugging', 'User onboarding funnel tracking', 'Feature flag rollouts'],
    skillsRequired: ['1-line script installation'],
    timeToLearn: '20 mins',
    recommendedFor: 'Launched founders who need to watch exactly where real users get stuck in their product onboarding.',
    tags: ['Analytics', 'Session Replays', 'Product OS', 'Funnels', 'Free Tier'],
    qualityScore: 96,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 9,
      openSource: 10,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 10,
      practicalValue: 10
    },
    qualityExplanation: 'Session recordings give early founders 100x more insight than raw charts. Free tier handles early traction easily.',
    lastVerifiedAt: '2026-08',
    source: 'Official PostHog Pricing',
    status: 'active',
    createdAt: '2026-01-10',
    updatedAt: '2026-08-22'
  },
  {
    id: 'res-penpot',
    title: 'Penpot (Open Source Design & Prototyping)',
    description: 'Web-based open-source design and prototyping tool that uses native web standards (SVG, CSS Flexbox, Grid), serving as a free alternative to Figma.',
    url: 'https://penpot.app',
    resourceType: 'tool',
    category: 'BUILD',
    subcategory: 'UI/UX & Design',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free cloud tier with unlimited files and teams, or self-host via Docker.',
    license: 'MPL-2.0',
    platform: ['Web Browser', 'Self-Hosted Docker'],
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP'],
    founderGoals: ['Design wireframes for free', 'CSS-native prototypes for developer handoff'],
    useCases: ['Landing page mockups', 'SaaS app wireframes', 'Vector icon editing'],
    skillsRequired: ['Visual layout'],
    timeToLearn: '30 mins',
    recommendedFor: 'Founders who want collaborative design files without Figma subscription seat fees.',
    tags: ['Design', 'Figma Alternative', 'Open Source', 'Wireframing', 'Prototyping'],
    qualityScore: 92,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 9,
      maintenance: 9,
      community: 8,
      recency: 9,
      practicalValue: 9
    },
    qualityExplanation: 'Generates real CSS flexbox and grid layouts, making the bridge from mockup to React code seamless.',
    lastVerifiedAt: '2026-08',
    source: 'Official Penpot Website',
    status: 'active',
    createdAt: '2026-02-10',
    updatedAt: '2026-08-15'
  },

  // ==========================================
  // 4. LEARN — ARTICLES & PLAYBOOKS (Problem-Solving)
  // ==========================================
  {
    id: 'res-art-mom-test',
    title: 'The Mom Test: How to Talk to Customers (Summary & Question Bank)',
    description: 'Rob Fitzpatrick’s definitive framework for validating startup ideas without asking leading questions that get fake polite validation.',
    url: 'https://robfitz.com/the-mom-test',
    resourceType: 'article',
    category: 'LEARN',
    subcategory: 'Customer Discovery Guides',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: 'Freely accessible core framework summary and question templates.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP'],
    founderGoals: ['Validate problem pain intensity', 'Stop hearing fake compliments from prospective users'],
    useCases: ['Conducting user interviews', 'Writing cold outreach messages', 'Qualifying customer intent'],
    skillsRequired: ['Active listening'],
    timeToLearn: '12 mins',
    recommendedFor: 'Founders about to write code or conduct customer discovery calls.',
    tags: ['Customer Interviews', 'Validation', 'Problem Discovery', 'The Mom Test', 'Playbook'],
    qualityScore: 99,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Essential reading. Prevents the #1 startup killer: building something nobody wants because people lied to be nice.',
    lastVerifiedAt: '2026-08',
    source: 'Rob Fitzpatrick / Founder Guides',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-20',
    articleDetails: {
      readingTimeMinutes: 8,
      problemSolved: 'How to ask customer interview questions so that even your mom cannot lie to you.',
      authorOrSource: 'Rob Fitzpatrick',
      isPaywalled: false
    },
    isFeatured: true
  },
  {
    id: 'res-art-do-things-dont-scale',
    title: 'Do Things That Don’t Scale',
    description: 'Paul Graham’s classic essay on manual user acquisition, founder-led recruitment, and providing unscalable delight to win early evangelists.',
    url: 'https://paulgraham.com/ds.html',
    resourceType: 'article',
    category: 'LEARN',
    subcategory: 'Startup Articles',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free on Paul Graham’s official website.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched'],
    founderGoals: ['Get first 10-100 users manually', 'Stop waiting for passive viral growth'],
    useCases: ['Direct founder sales', 'Manual user onboarding', 'Overcoming early growth paralysis'],
    skillsRequired: ['Founder grit'],
    timeToLearn: '15 mins',
    recommendedFor: 'Founders waiting for users to magically show up instead of going out to manually onboard them.',
    tags: ['Paul Graham', 'Y Combinator', 'Early Growth', 'Distribution', 'Customer Onboarding'],
    qualityScore: 98,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 8,
      practicalValue: 10
    },
    qualityExplanation: 'Timeless guidance explaining why manual hustle beats complex marketing funnels in the first 100 users.',
    lastVerifiedAt: '2026-08',
    source: 'Paul Graham Official Archive',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-15',
    articleDetails: {
      readingTimeMinutes: 14,
      problemSolved: 'How early stage startups bootstrap initial user growth without an existing brand or ad budget.',
      authorOrSource: 'Paul Graham (Y Combinator)',
      isPaywalled: false
    },
    isFeatured: true
  },
  {
    id: 'res-art-first-1000-users',
    title: 'How the Biggest Consumer & SaaS Apps Got Their First 1,000 Users',
    description: 'Lenny Rachitsky’s deep-dive research analyzing 100+ top companies across the 7 primary distribution channels used to acquire first 1,000 users.',
    url: 'https://www.lennysnewsletter.com/p/how-the-biggest-consumer-apps-got',
    resourceType: 'article',
    category: 'LEARN',
    subcategory: 'Growth Articles',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: 'Free un-gated edition on Lenny’s Substack.',
    difficulty: 'Intermediate',
    technicalLevel: 'Non-Technical',
    startupStages: ['Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Identify repeatable acquisition channels', 'Stop guessing where customers hang out'],
    useCases: ['Cold outreach', 'Community seeding', 'Product Hunt launches', 'Build-in-public'],
    skillsRequired: ['Marketing & Distribution'],
    timeToLearn: '20 mins',
    recommendedFor: 'Founders who launched their product and now need a concrete distribution channel playbook.',
    tags: ['Lenny Rachitsky', 'First 1000 Users', 'Distribution', 'Case Studies', 'Zero Budget Growth'],
    qualityScore: 97,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 9,
      community: 10,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Breaks down acquisition into 7 actionable tactics with real founder case studies and zero fluff.',
    lastVerifiedAt: '2026-08',
    source: 'Lenny’s Newsletter (Free Edition)',
    status: 'active',
    createdAt: '2026-01-20',
    updatedAt: '2026-08-20',
    articleDetails: {
      readingTimeMinutes: 18,
      problemSolved: 'Choosing the right initial customer acquisition channel based on your product category.',
      authorOrSource: 'Lenny Rachitsky',
      isPaywalled: false
    }
  },
  {
    id: 'res-art-retention-loops',
    title: 'Retention Cohorts & Diagnostics: Why Retention is King',
    description: 'Tactical guide on measuring week-over-week cohort retention, identifying the drop-off cliff, and fixing activation before scaling acquisition.',
    url: 'https://brianbalfour.com/essays/retention-cohorts',
    resourceType: 'article',
    category: 'LEARN',
    subcategory: 'Product Articles',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: 'Free guide on Brian Balfour’s publication.',
    difficulty: 'Intermediate',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Diagnose leaky bucket churn', 'Calculate true 30-day retention curve'],
    useCases: ['Cohort curve flattening', 'Onboarding milestone activation analysis'],
    skillsRequired: ['Basic metrics understanding'],
    timeToLearn: '15 mins',
    recommendedFor: 'Founders with active users whose numbers keep dropping after week 2.',
    tags: ['Retention', 'Churn', 'Cohorts', 'Product Market Fit', 'Metrics'],
    qualityScore: 95,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 9,
      community: 9,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Clearly explains why pouring traffic into a leaky bucket fails, and provides mathematical rules to spot real product-market fit.',
    lastVerifiedAt: '2026-08',
    source: 'Reforge & Brian Balfour Archive',
    status: 'active',
    createdAt: '2026-02-01',
    updatedAt: '2026-08-15',
    articleDetails: {
      readingTimeMinutes: 12,
      problemSolved: 'How to determine if your product actually retains users before spending money on growth.',
      authorOrSource: 'Brian Balfour / Reforge',
      isPaywalled: false
    }
  },
  {
    id: 'res-art-saas-pricing',
    title: 'SaaS Pricing for Bootstrappers: The 10x Value Equation',
    description: 'Practical guide to pricing your early SaaS product, eliminating the $5/month trap, and structuring tiers that customers gladly pay for.',
    url: 'https://robwalling.com/saas-pricing-guide',
    resourceType: 'article',
    category: 'LEARN',
    subcategory: 'Pricing Guides',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free article on Rob Walling’s blog.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Building MVP', 'Launched', 'First Revenue'],
    founderGoals: ['Price based on value not cost', 'Stop undercharging out of impostor syndrome'],
    useCases: ['Setting initial pricing tiers', 'Annual vs monthly discounts', 'Handling pricing objections'],
    skillsRequired: ['Business logic'],
    timeToLearn: '10 mins',
    recommendedFor: 'Founders scared to ask for money or charging $5 for a tool that saves companies $500/month.',
    tags: ['Pricing', 'Monetization', 'Bootstrapping', 'Rob Walling', 'SaaS Economics'],
    qualityScore: 94,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 9,
      community: 9,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Direct, actionable framework specifically tailored for bootstrapped founders with ₹0 or small budgets.',
    lastVerifiedAt: '2026-08',
    source: 'MicroConf / Rob Walling',
    status: 'active',
    createdAt: '2026-02-15',
    updatedAt: '2026-08-20',
    articleDetails: {
      readingTimeMinutes: 9,
      problemSolved: 'How to structure pricing tiers that convert without underpricing your core product.',
      authorOrSource: 'Rob Walling (MicroConf)',
      isPaywalled: false
    }
  },

  // ==========================================
  // 5. READ — FREE FOUNDER NEWSLETTERS
  // ==========================================
  {
    id: 'res-news-tldr',
    title: 'TLDR Tech & Startups',
    description: 'Free daily email newsletter summarizing the most interesting news in tech, AI, startups, and software engineering in 5 minutes.',
    url: 'https://tldr.tech',
    resourceType: 'newsletter',
    category: 'READ',
    subcategory: 'Technology & Startup Newsletters',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free daily newsletter. No paywall.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Stay updated on tech trends in 5 minutes', 'Discover new tools & AI breakthroughs'],
    useCases: ['Daily morning reading', 'Tracking software market movements'],
    skillsRequired: ['Reading'],
    timeToLearn: '5 mins/day',
    recommendedFor: 'Founders who want a fast, high-signal, zero-fluff daily tech and AI briefing.',
    tags: ['Newsletter', 'Daily Tech', 'AI', 'Startups', 'Free Subscription'],
    qualityScore: 96,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 9,
      maintenance: 10,
      community: 10,
      recency: 10,
      practicalValue: 9
    },
    qualityExplanation: 'Verified 100% free daily email with 1.25M+ subscribers. Summarizes major tech releases without long sponsored fluff.',
    lastVerifiedAt: '2026-08',
    source: 'TLDR.tech Official',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-28',
    newsletterDetails: {
      newsletterFrequency: 'Daily',
      subscriptionUrl: 'https://tldr.tech/signup',
      isFree: true,
      topics: ['Startups', 'AI Models', 'Software Engineering', 'Big Tech'],
      audienceLevel: 'All Founders'
    },
    isFeatured: true
  },
  {
    id: 'res-news-product-hunt',
    title: 'Product Hunt Daily',
    description: 'Daily newsletter covering top product launches, maker interviews, emerging tech trends, and community favorites.',
    url: 'https://www.producthunt.com/newsletter',
    resourceType: 'newsletter',
    category: 'READ',
    subcategory: 'Product Newsletters',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free daily product launch newsletter.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue'],
    founderGoals: ['Study successful product launches', 'Find emerging tool niches'],
    useCases: ['Competitive research', 'Launch strategy benchmarking'],
    skillsRequired: ['Product awareness'],
    timeToLearn: '5 mins/day',
    recommendedFor: 'Founders preparing for their own launch or looking for product inspiration.',
    tags: ['Product Hunt', 'Launches', 'Makers', 'Product Inspiration', 'Free'],
    qualityScore: 93,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 9,
      founderUsefulness: 9,
      maintenance: 10,
      community: 10,
      recency: 10,
      practicalValue: 9
    },
    qualityExplanation: 'Great for seeing how peer founders position their value propositions and video demos.',
    lastVerifiedAt: '2026-08',
    source: 'Product Hunt Official',
    status: 'active',
    createdAt: '2026-01-05',
    updatedAt: '2026-08-28',
    newsletterDetails: {
      newsletterFrequency: 'Daily',
      subscriptionUrl: 'https://www.producthunt.com/newsletter',
      isFree: true,
      topics: ['New Products', 'Maker Stories', 'Launch Strategies', 'SaaS Tools'],
      audienceLevel: 'All Founders'
    }
  },
  {
    id: 'res-news-yc-digest',
    title: 'Y Combinator Startup Library & Digest',
    description: 'Official YC tactical essays, videos, and Startup School updates from partners on problem validation, pricing, and scaling.',
    url: 'https://www.ycombinator.com/library',
    resourceType: 'newsletter',
    category: 'READ',
    subcategory: 'Startup Newsletters',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free library and email curriculum from Y Combinator.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Learn YC standard operating playbooks', 'Understand investor & customer expectations'],
    useCases: ['Weekly founder study', 'Co-founder alignment discussions'],
    skillsRequired: ['Startup curiosity'],
    timeToLearn: '15 mins/week',
    recommendedFor: 'Any founder building a high-growth company or applying to accelerator programs.',
    tags: ['Y Combinator', 'Startup School', 'Strategy', 'Fundraising', 'Free Playbooks'],
    qualityScore: 98,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Gold standard startup advice backed by data from thousands of successful venture and bootstrapped companies.',
    lastVerifiedAt: '2026-08',
    source: 'Y Combinator Official Library',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-25',
    newsletterDetails: {
      newsletterFrequency: 'Weekly',
      subscriptionUrl: 'https://www.startupschool.org',
      isFree: true,
      topics: ['YC Lectures', 'Founder Playbooks', 'Problem Validation', 'Pitch Decks'],
      audienceLevel: 'Early Stage'
    },
    isFeatured: true
  },
  {
    id: 'res-news-first-round',
    title: 'First Round Review (Free Bi-Weekly Digest)',
    description: 'Long-form tactical essays and management playbooks written directly by top operating leaders from Notion, Figma, Stripe, and Airbnb.',
    url: 'https://review.firstround.com',
    resourceType: 'newsletter',
    category: 'READ',
    subcategory: 'Founder Newsletters',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free publication. No paywall.',
    difficulty: 'Intermediate',
    technicalLevel: 'Non-Technical',
    startupStages: ['Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Master tactical hiring, sales, and product strategy', 'Deep dive into real operating playbooks'],
    useCases: ['Scaling sales teams', 'Customer success operations', 'Product management frameworks'],
    skillsRequired: ['Business operations'],
    timeToLearn: '20 mins/article',
    recommendedFor: 'Founders looking for deep, practitioner-level operating wisdom rather than shallow listicles.',
    tags: ['First Round Review', 'Operations', 'Leadership', 'Product Strategy', 'Free Articles'],
    qualityScore: 97,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 10,
      maintenance: 9,
      community: 9,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Widely considered the Harvard Business Review for tech startups. Extremely thorough and completely free.',
    lastVerifiedAt: '2026-08',
    source: 'First Round Capital',
    status: 'active',
    createdAt: '2026-01-15',
    updatedAt: '2026-08-22',
    newsletterDetails: {
      newsletterFrequency: 'Bi-weekly',
      subscriptionUrl: 'https://review.firstround.com/newsletter',
      isFree: true,
      topics: ['Hiring', 'Go-To-Market', 'Product Strategy', 'Engineering Leadership'],
      audienceLevel: 'Growth & Product'
    }
  },
  {
    id: 'res-news-bytebytego',
    title: 'ByteByteGo (Free System Architecture Digest)',
    description: 'Alex Xu’s visual breakdowns of system architecture, distributed databases, cloud scale, and real-world backend infrastructure.',
    url: 'https://bytebytego.com',
    resourceType: 'newsletter',
    category: 'READ',
    subcategory: 'Engineering & Technical Newsletters',
    pricingType: 'free_tier',
    isOpenSource: false,
    isFree: false,
    hasFreeTier: true,
    freeTierDescription: 'Weekly free visual system architecture deep-dive emails.',
    difficulty: 'Intermediate',
    technicalLevel: 'Technical',
    startupStages: ['Building MVP', 'Launched', 'Growing'],
    founderGoals: ['Understand scalable backend architecture visually', 'Make correct database and caching choices'],
    useCases: ['System design decisions', 'Choosing SQL vs NoSQL vs Caching', 'Cloud architecture optimization'],
    skillsRequired: ['Basic software architecture'],
    timeToLearn: '10 mins/week',
    recommendedFor: 'Technical founders architecting backends that will need to scale cost-effectively.',
    tags: ['System Design', 'Architecture', 'Databases', 'Backend Scale', 'ByteByteGo'],
    qualityScore: 95,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 9,
      openSource: 5,
      docQuality: 10,
      founderUsefulness: 9,
      maintenance: 10,
      community: 10,
      recency: 10,
      practicalValue: 9
    },
    qualityExplanation: 'Visual diagrams make complex engineering concepts intuitive in minutes.',
    lastVerifiedAt: '2026-08',
    source: 'ByteByteGo Substack',
    status: 'active',
    createdAt: '2026-02-01',
    updatedAt: '2026-08-26',
    newsletterDetails: {
      newsletterFrequency: 'Weekly',
      subscriptionUrl: 'https://blog.bytebytego.com',
      isFree: true,
      topics: ['System Design', 'Postgres vs Mongo', 'Caching', 'Microservices', 'Cloud Architecture'],
      audienceLevel: 'Technical Founders'
    }
  },

  // ==========================================
  // 6. DISCOVER — OPEN SOURCE TEMPLATES & COMMUNITIES
  // ==========================================
  {
    id: 'res-disc-next-saas',
    title: 'Next.js SaaS Starter (Open Source)',
    description: 'Production-ready open-source Next.js starter repository with Supabase Auth, Stripe billing, Tailwind CSS, and dashboard layout.',
    url: 'https://github.com/shadcn-ui/taxonomy',
    resourceType: 'repository',
    category: 'DISCOVER',
    subcategory: 'Starter Templates & Boilerplates',
    pricingType: 'open_source',
    isOpenSource: true,
    isFree: true,
    hasFreeTier: true,
    freeTierDescription: '100% Free under MIT license. Clone and deploy anywhere.',
    license: 'MIT',
    platform: ['Next.js', 'React', 'TypeScript', 'Tailwind'],
    difficulty: 'Beginner',
    technicalLevel: 'Semi-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP'],
    founderGoals: ['Skip weeks of boilerplate authentication code', 'Launch working MVP today'],
    useCases: ['SaaS app foundations', 'User login & settings', 'Stripe checkout flow'],
    skillsRequired: ['React / TypeScript basics'],
    timeToLearn: '30 mins',
    recommendedFor: 'Founders starting a new web app who want to skip setting up authentication, database schemas, and billing from scratch.',
    tags: ['SaaS Boilerplate', 'Next.js', 'TypeScript', 'Open Source', 'MIT'],
    qualityScore: 96,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 10,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 9,
      community: 10,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Saves 40+ hours of boilerplate setup. Clean architecture and zero vendor lock-in.',
    lastVerifiedAt: '2026-08',
    source: 'GitHub Open Source Community',
    status: 'active',
    createdAt: '2026-01-10',
    updatedAt: '2026-08-20',
    isFeatured: true
  },
  {
    id: 'res-disc-indie-hackers',
    title: 'Indie Hackers Community & Revenue Database',
    description: 'Community of bootstrapped founders sharing verified revenue numbers, transparent growth logs, launch playbooks, and honest feedback.',
    url: 'https://www.indiehackers.com',
    resourceType: 'community',
    category: 'DISCOVER',
    subcategory: 'Founder Communities',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: '100% Free to join, post, and read verified founder case studies.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched', 'First Revenue', 'Growing'],
    founderGoals: ['Find beta testers', 'Learn from profitable solo bootstrappers', 'Build in public'],
    useCases: ['Product feedback posts', 'Milestone celebrations', 'Finding co-founders & early adopters'],
    skillsRequired: ['Community engagement'],
    timeToLearn: 'Ongoing',
    recommendedFor: 'Solo founders wanting a supportive, non-venture-capital-obsessed community focused on cash-flow profitability.',
    tags: ['Indie Hackers', 'Bootstrapping', 'Community', 'Case Studies', 'Zero Budget'],
    qualityScore: 94,
    qualityBreakdown: {
      relevance: 10,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 9,
      community: 10,
      recency: 9,
      practicalValue: 9
    },
    qualityExplanation: 'The premier hub for bootstrappers. Transparent revenue milestones keep founders grounded in real economics.',
    lastVerifiedAt: '2026-08',
    source: 'Indie Hackers Official',
    status: 'active',
    createdAt: '2026-01-01',
    updatedAt: '2026-08-26'
  },
  {
    id: 'res-disc-github-pack',
    title: 'GitHub for Startups & Developer Pack',
    description: 'Curated collection of free developer tools, cloud infrastructure credits, domain vouchers, and continuous integration runners.',
    url: 'https://github.com/enterprise/startups',
    resourceType: 'program',
    category: 'DISCOVER',
    subcategory: 'Startup Programs & Credits',
    pricingType: 'free',
    isOpenSource: false,
    isFree: true,
    hasFreeTier: false,
    freeTierDescription: 'Free access to GitHub Enterprise, Copilot credits, and partner cloud vouchers for eligible early startups.',
    difficulty: 'Beginner',
    technicalLevel: 'Non-Technical',
    startupStages: ['Idea', 'Validating', 'Building MVP', 'Launched'],
    founderGoals: ['Save thousands on developer tooling', 'Free CI/CD compute minutes'],
    useCases: ['Automated testing pipelines', 'Security vulnerability scanning', 'Free domain vouchers'],
    skillsRequired: ['GitHub account'],
    timeToLearn: '15 mins',
    recommendedFor: 'Early startups wanting to access enterprise-grade DevOps tools with ₹0 overhead.',
    tags: ['GitHub', 'Free Credits', 'Startup Pack', 'DevOps', 'Free Tools'],
    qualityScore: 95,
    qualityBreakdown: {
      relevance: 9,
      freeAccessibility: 10,
      openSource: 5,
      docQuality: 9,
      founderUsefulness: 10,
      maintenance: 10,
      community: 10,
      recency: 9,
      practicalValue: 10
    },
    qualityExplanation: 'Substantial cost savings for early development. Backed by verified developer ecosystems.',
    lastVerifiedAt: '2026-08',
    source: 'GitHub Official Startups Program',
    status: 'active',
    createdAt: '2026-01-10',
    updatedAt: '2026-08-20'
  }
];
